name: build and test UnitTestProject

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - 'UnitTestProject/**'

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore UnitTestProject/UnitTestProject.csproj

    - name: Build the test project
      run: dotnet build UnitTestProject/UnitTestProject.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test UnitTestProject/UnitTestProject.csproj --no-restore --verbosity normal
